services:

  postgres-source:
    image: postgres:16
    container_name: ecommerce-postgres-source
    environment:
      POSTGRES_DB: ${SOURCE_DB_NAME}
      POSTGRES_USER: ${SOURCE_DB_USER}
      POSTGRES_PASSWORD: ${SOURCE_DB_PASSWORD}
    ports:
      - "${SOURCE_DB_PORT}:5432"
    volumes:
      - source_postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  postgres-target:
    image: postgres:16
    container_name: ecommerce-postgres-target
    environment:
      POSTGRES_DB: ${TARGET_DB_NAME}
      POSTGRES_USER: ${TARGET_DB_USER}
      POSTGRES_PASSWORD: ${TARGET_DB_PASSWORD}
    ports:
      - "${TARGET_DB_PORT}:5432"
    volumes:
      - target_postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  airflow:
    image: apache/airflow:3.0.2
    container_name: ecommerce-airflow
    command: standalone
    restart: unless-stopped

    depends_on:
      - postgres-source
      - postgres-target

    environment:
      AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION: "true"
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__CORE__LOAD_EXAMPLES: "false"
      AIRFLOW__CORE__DEFAULT_TIMEZONE: Asia/Kolkata
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: sqlite:////opt/airflow/airflow.db

      PYTHONPATH: /opt/airflow/project

      SOURCE_DB_HOST: postgres-source
      SOURCE_DB_PORT: "5432"
      SOURCE_DB_NAME: ${SOURCE_DB_NAME}
      SOURCE_DB_USER: ${SOURCE_DB_USER}
      SOURCE_DB_PASSWORD: ${SOURCE_DB_PASSWORD}

      TARGET_DB_HOST: postgres-target
      TARGET_DB_PORT: "5432"
      TARGET_DB_NAME: ${TARGET_DB_NAME}
      TARGET_DB_USER: ${TARGET_DB_USER}
      TARGET_DB_PASSWORD: ${TARGET_DB_PASSWORD}

    ports:
      - "8081:8080"

    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - ./airflow/logs:/opt/airflow/logs
      - ./airflow/pluginsdir:/opt/airflow/plugins
      - ./:/opt/airflow/project


volumes:
  source_postgres_data:
  target_postgres_data: